### ISSUE TITLE
how to receive the updated files

### ISSUE THREAD

**Issue by Aeronote** [microstack-IoT/python3-microstacknode#4]
hi, i am quite new to raspberry and the microstack modules. i also just figured out i have one of the wrongly manufactured boards. anyways, how can i update repository to the one here on github? thanks

**Comment by tompreston** [comment]
Hi, we're in the process of getting the packages in the Raspbian repositories updated. I'll post back when it's updated. :)

**Comment by tompreston** [comment]
Also, the most up to date files will be in PyPi which you can install using `pip`.
