### ISSUE TITLE
Problem with MICROSTACK GPS L80-M39

### ISSUE THREAD

**Issue by tuning1001** [microstack-IoT/python3-microstacknode#5]
Hello, I have a little problem with MICROSTACK GPS L80-M39 does not want to walk. With minicom I get values but using gpscat.py element14 python program I have this error appears:
![11798478_10207594121236993_65716463_n](https://cloud.githubusercontent.com/assets/3811430/8874427/349dcec6-3211-11e5-9485-5cf27c0f69df.jpg)

pi@raspberrypi ~ $ sudo python3 /usr/share/doc/python3-microstacknode/examples/gpscat.py
Traceback (most recent call last):
File "/usr/share/doc/python3-microstacknode/examples/gpscat.py", line 9, in <module>
gogll = gps.gpgll
File "/usr/lib/python3/dist-packages/microstacknode/gps/l80gps.py", line 106, in gpgll
raise DataInvalidError("Indicated by data_valid field.")
microstacknode.gps.l80gps.DataInvalidError : Indicated by data_valid field.

I'm also testing it with minicom

![11759478_10207594352762781_1577389906_n](https://cloud.githubusercontent.com/assets/3811430/8874535/296e2f86-3212-11e5-9694-13b59029c5c1.jpg) 

Thank you

**Comment by tompreston** [comment]
A `microstacknode.gps.l80gps.DataInvalidError` error means that your data is invalid -- it looks like you haven't got a fix with the GPS. You will know when Microstack GPS has a fix when the red LED on the orange board flashes.

You can see this in `minicom` too. Most of the data is empty (just commas separating no data). When you get a GPS fix, minicom will return useful data and you will no longer get the data invalid error Python.

Try moving the GPS unit closer to a window or try it outside.

**Comment by tuning1001** [comment]
Yes it works thanks thanks :D
